/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pnlProcesarPedidoCliente.java
 *
 * Created on 20/06/2011, 21:46:13
 */
package Presentacion.ProcesarPedidoCliente;

import Negocio.ProcesarPedidoCliente;
import Presentacion.SIPGUIView;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JPanel;

/**
 *
 * @author NicolasM
 */
public class pnlProcesarPedidoCliente extends javax.swing.JPanel {

    private static final String[] pasosProceso = {"Cliente y Prioridad", "Productos", "Comprometer Stock", "Emitir pedido"};
    
    private ProcesarPedidoCliente proceso = new ProcesarPedidoCliente();
    private ArrayList<JPanel> panelesProceso;
    
    /** Creates new form pnlProcesarPedidoCliente */
    public pnlProcesarPedidoCliente() {
        initComponents();
        
        this.setLayout(new BorderLayout());
        SIPGUIView.getInstance().RegistrarPasosProceso(pasosProceso);
        
        ArrayList<JPanel> pasos = new ArrayList<JPanel>();
        pasos.add(new pnlPPC_SeleccionClientePrioridad(this, proceso, 0));
        pasos.add(new pnlPPC_SeleccionProductosCantidad(this, proceso, 1));
        pasos.add(new pnlPPC_DisponibilidadProductos(this, proceso, 2));
        
        panelesProceso = pasos;
        
        this.add(panelesProceso.get(0));
        panelesProceso.get(0).setVisible(true);
        //this.setBorder(BorderFactory.createBevelBorder(0));
        //panelesProceso[0].setBorder(BorderFactory.createBevelBorder(0));
    }

    public void SiguientePaso(int pasoActual){
        panelesProceso.get(pasoActual).setVisible(false);
        this.remove(panelesProceso.get(pasoActual));
        
        int proximoPaso = pasoActual + 1;
        if(panelesProceso.size() == proximoPaso){
            //Alcanzó el último paso, elimina el detalle de pasos
            SIPGUIView.getInstance().EliminarProceso();
            //TODO: quitar this del mainPanel de SIPGUIView
        }else{
           panelesProceso.get(proximoPaso).setVisible(true);
           this.add(panelesProceso.get(proximoPaso));
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(Presentacion.SIPGUIApp.class).getContext().getResourceMap(pnlProcesarPedidoCliente.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
